import os
from dotenv import load_dotenv 

# loading variables from .env file
load_dotenv()

AWS_BUCKET_NAME = os.getenv("AWS_BUCKET_NAME")
AWS_ATHENA_STAGING_DATABASE = os.getenv("AWS_ATHENA_STAGING_DATABASE")

GEOGRAPHY_TABLE_NAME = 'geography'

QUERY_CREATE_EXTERNAL_GEOGRAPHY_TABLE_STAGING: str = f"""
CREATE EXTERNAL TABLE {AWS_ATHENA_STAGING_DATABASE}.{GEOGRAPHY_TABLE_NAME}_ext(
  city          string COMMENT 'The name of the city/town as a Unicode string',
  city_ascii    string COMMENT 'The name of the city as an ASCII string',
  lat           double COMMENT 'The latitude of the city/town',
  lng           double COMMENT 'The longitude of the city/town',
  country       string COMMENT 'The name of the country',
  iso2          string COMMENT 'The alpha-2 iso code of the country',
  iso3          string COMMENT 'TLC Taxi Zone in which the taximeter was disengaged',
  admin_name    string COMMENT 'The name of the highest level administration region of the city town',
  capital       string COMMENT 'The name of the country s capital',
  population    int COMMENT 'An estimate of the city s urban population',
  id            int COMMENT 'A 10-digit unique id generated by SimpleMaps'
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim' = ',', 'skip.header.line.count'='1')
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 's3://{AWS_BUCKET_NAME}/{GEOGRAPHY_TABLE_NAME}/csv/'
TBLPROPERTIES ('classification' = 'csv');
"""

QUERY_DROP_GEOGRAPHY_TABLE_STAGING : str = f"""
DROP TABLE IF EXISTS {AWS_ATHENA_STAGING_DATABASE}.{GEOGRAPHY_TABLE_NAME}_ext;
"""