version: 2

sources:
  - name: staging
    database: AwsDataCatalog 
    schema: infrabel_staging_db

    tables:
      - name: punctuality_iceberg
      - name: station_ext
      - name: stop_ext